export const PROTOCOL_OPTIONS = [
  { value: 'responses', label: 'Responses' },
  { value: 'chat_completions', label: 'Chat Completions' },
];

export const LANGUAGE_OPTIONS = [
  { value: 'en', label: 'English' },
  { value: 'zh-CN', label: '简体中文' },
  { value: 'zh-TW', label: '繁體中文' },
  { value: 'ja', label: '日本語' },
  { value: 'ko', label: '한국어' },
  { value: 'fr', label: 'Français' },
  { value: 'de', label: 'Deutsch' },
  { value: 'es', label: 'Español' },
];

const ZH_TOOLTIPS = {
  protocol: '选择模型接口的请求格式。一般按服务商文档选择 Responses 或 Chat Completions。',
  endpointPath: '接口路径会和 Base URL 拼接成完整请求地址。切换协议时会自动填入推荐路径。',
  temperature: '控制生成内容的发散程度。数值越低越稳定，当前默认值 0.1 更适合生成严格参考型 DESIGN.md。',
  maxOutputTokens: '限制模型最多生成多少内容。当前默认值提高到 5200，以便输出更完整的长篇设计系统文档。',
  timeoutMs: '远程模型请求最长等待时间。超时后会自动回退到本地规则分析。',
  language: '选择 DESIGN.md 的生成结果输出语言。默认英文，当前效果最好；除非有明确需要，不建议修改。',
  systemPromptOverride: '高级选项。填写后会替换默认系统提示词，用于自定义模型写作风格。',
  redactInputs: '开启后会尽量避免采集表单输入值，降低发送敏感内容的风险。',
  includeColorTokens: '在文档中包含页面识别到的主要颜色值。',
  includeTypographyTokens: '在文档中包含页面识别到的字体信息。',
  includeSpacingHeuristics: '根据页面结构推断常见间距节奏，结果是启发式分析，不等同于真实设计 token。',
  includeRawAuditAppendix: '在文档附录中加入原始分析摘要，方便排查生成结果依据。',
  includeFrontmatter: '在 Markdown 文件顶部加入机器可读的元数据标题信息，便于后续脚本或文档系统处理。',
  maxDomNodes: '限制最多分析多少个页面节点。复杂页面可适当调高，但会增加处理量。',
  filenameTemplate: '导出文件名模板。{domain} 会被替换为当前网站域名。',
  autoDownloadAfterGeneration: '开启后分析完成会直接下载 DESIGN.md，不再额外确认。',
};

export const TOOLTIP_COPY = ZH_TOOLTIPS;

const TOOLTIP_COPY_BY_LANGUAGE = {
  'zh-CN': ZH_TOOLTIPS,
  'zh-TW': ZH_TOOLTIPS,
  en: {
    protocol: 'Choose the request format required by your model provider.',
    endpointPath: 'This path is appended to the Base URL. Switching protocol fills the recommended path.',
    temperature: 'Controls how creative the model output is. Lower values are more stable.',
    maxOutputTokens: 'Limits the maximum generated content. Higher values may increase cost.',
    timeoutMs: 'Maximum wait time for the remote model. Timeout falls back to local analysis.',
    language: 'English is the recommended default and currently produces the best results. Change this only if you explicitly need another output language.',
    uiLanguage: 'Choose the display language of this extension interface.',
    systemPromptOverride: 'Advanced option. Replaces the default system prompt.',
    redactInputs: 'Avoids collecting form input values where possible to reduce sensitive data risk.',
    includeColorTokens: 'Includes the main colors detected on the page.',
    includeTypographyTokens: 'Includes detected font information.',
    includeSpacingHeuristics: 'Infers spacing rhythm from page structure. This is heuristic, not real design tokens.',
    includeRawAuditAppendix: 'Adds an appendix with raw analysis notes to explain the generated result.',
    includeFrontmatter: 'Adds machine-readable metadata at the top of the Markdown file.',
    maxDomNodes: 'Limits how many DOM nodes are analyzed.',
    filenameTemplate: 'Export filename template. {domain} is replaced by the current domain.',
    autoDownloadAfterGeneration: 'Downloads DESIGN.md automatically after generation.',
  },
};

export const UI_MESSAGES = {
  'zh-CN': {
    'settings.title': 'DESIGN.md Extractor 设置',
    'settings.heroEyebrow': '混合分析器',
    'settings.heroCopy':
      '插件默认可在本地规则模式下工作。填写模型地址、API Key、模型名和协议后，会自动切换到增强分析模式。',
    'settings.aiEyebrow': '模型',
    'settings.analysisEyebrow': '分析',
    'settings.rulesEyebrow': '规则',
    'settings.aiSettings': '模型连接参数',
    'settings.enableAi': '启动 AI 分析生成',
    'settings.enableAiHint': '推荐开启，生成质量明显更高',
    'settings.uiLanguage': '当前语言',
    'settings.protocol': '协议',
    'settings.baseUrl': 'Base URL',
    'settings.model': '模型名',
    'settings.endpointPath': 'Endpoint Path',
    'settings.apiKey': 'API Key',
    'settings.temperature': 'Temperature',
    'settings.maxOutputTokens': 'Max Output Tokens',
    'settings.timeoutMs': 'Timeout (ms)',
    'settings.outputLanguage': '输出语言',
    'settings.systemPromptOverride': 'System Prompt Override',
    'settings.analysisTitle': '分析与导出偏好',
    'settings.redactInputs': '脱敏输入内容',
    'settings.autoDownloadAfterGeneration': '自动下载生成结果',
    'settings.includeColorTokens': '包含颜色 token',
    'settings.includeTypographyTokens': '包含字体 token',
    'settings.includeSpacingHeuristics': '包含间距启发式',
    'settings.includeRawAuditAppendix': '附加原始审计附录',
    'settings.includeFrontmatter': '包含 Frontmatter',
    'settings.maxDomNodes': '最大节点数',
    'settings.filenameTemplate': '文件名模板',
    'settings.rulesTitle': '站点规则与隐私说明',
    'settings.siteAllowlist': '允许列表（每行一个域名片段，可留空）',
    'settings.siteBlocklist': '排除列表（每行一个域名片段）',
    'settings.privacyNote':
      '启用 AI 增强分析时，插件会发送结构化页面摘要到你配置的远程模型接口，不会直接上传完整原始 DOM 文件。',
    'settings.saveButton': '保存设置',
    'settings.unsaved': '尚未保存。',
    'settings.saving': '正在保存配置...',
    'settings.saved': '已保存。未配置完整 AI 参数时，插件会自动使用本地规则分析。',
    'settings.aiReady': '当前已具备增强分析所需的基础参数。',
    'settings.aiFallback': '当前参数不完整，插件将自动退回本地规则分析。',
    'settings.validationRequired': '启用 AI 增强分析时，请先补全必要参数：{fields}。',
    'settings.enableAiPromptTitle': '当前未启用 AI 分析生成',
    'settings.enableAiPromptBody':
      '如果保持关闭，插件会优先使用本地模式，生成质量会明显弱于 AI 分析。',
    'settings.enableAiPromptEnable': '启用 AI 并保存',
    'settings.enableAiPromptKeepLocal': '继续以本地模式保存',
    'settings.enableAiPromptCancel': '取消',
    'popup.currentPage': '当前页面',
    'popup.title': 'DESIGN.md Extractor',
    'popup.localMode': '本地模式 · 基础稿',
    'popup.hybridMode': 'AI 模式 · 增强提炼',
    'popup.primaryAction': '主操作',
    'popup.actionTitle': '分析当前页面并直接导出',
    'popup.actionCopy':
      '未配置 AI 时自动使用本地规则分析。补全模型地址、API Key、模型名和协议后，会自动启用增强分析。',
    'popup.analyzeButton': '分析并生成 DESIGN.md',
    'popup.settingsButton': '设置',
    'popup.waiting': '等待开始。',
    'popup.latestResult': '最近一次分析',
    'popup.noFile': '尚未生成文件',
    'popup.noResult': '尚未执行分析。',
    'popup.unsupported': '当前页面不可分析，仅支持 http/https 页面。',
    'popup.running': '正在采集页面并生成 DESIGN.md...',
    'popup.done': '分析完成，文件已下载到本地。',
    'popup.failed': '分析未完成。',
    'popup.initFailed': '初始化失败。',
    'popup.noPage': '未检测到当前页面。',
    'popup.localPromptTitle': '当前正在使用本地模式',
    'popup.localPromptBody':
      '本地模式会直接输出基础版 DESIGN.md。连接 AI 后，结构完整度、语言质量和参考文档拟合度都会更好。',
    'popup.localPromptContinue': '继续本地生成',
    'popup.localPromptPrimary': '去设置 AI',
    'popup.localPromptSwitchAi': '切换到 AI 模式',
    'popup.localPromptCancel': '稍后再说',
  },
  en: {
    'settings.title': 'DESIGN.md Extractor Settings',
    'settings.heroEyebrow': 'Hybrid Analyzer',
    'settings.heroCopy':
      'The extension works locally by default. Add model URL, API key, model, and protocol to enable enhanced analysis.',
    'settings.aiEyebrow': 'Model',
    'settings.analysisEyebrow': 'Analysis',
    'settings.rulesEyebrow': 'Rules',
    'settings.aiSettings': 'Model Connection',
    'settings.enableAi': 'Enable AI Analysis',
    'settings.enableAiHint': 'Recommended for markedly better output quality',
    'settings.uiLanguage': 'Current language',
    'settings.protocol': 'Protocol',
    'settings.baseUrl': 'Base URL',
    'settings.model': 'Model',
    'settings.endpointPath': 'Endpoint Path',
    'settings.apiKey': 'API Key',
    'settings.temperature': 'Temperature',
    'settings.maxOutputTokens': 'Max Output Tokens',
    'settings.timeoutMs': 'Timeout (ms)',
    'settings.outputLanguage': 'Output language',
    'settings.systemPromptOverride': 'System Prompt Override',
    'settings.analysisTitle': 'Analysis and Export Preferences',
    'settings.redactInputs': 'Redact input content',
    'settings.autoDownloadAfterGeneration': 'Auto-download result',
    'settings.includeColorTokens': 'Include color tokens',
    'settings.includeTypographyTokens': 'Include typography tokens',
    'settings.includeSpacingHeuristics': 'Include spacing heuristics',
    'settings.includeRawAuditAppendix': 'Append raw audit appendix',
    'settings.includeFrontmatter': 'Include Frontmatter',
    'settings.maxDomNodes': 'Max DOM nodes',
    'settings.filenameTemplate': 'Filename template',
    'settings.rulesTitle': 'Site Rules and Privacy',
    'settings.siteAllowlist': 'Allowlist (one domain fragment per line, optional)',
    'settings.siteBlocklist': 'Blocklist (one domain fragment per line)',
    'settings.privacyNote':
      'When AI analysis is enabled, the extension sends a structured page summary to your configured model endpoint, not the full raw DOM.',
    'settings.saveButton': 'Save settings',
    'settings.unsaved': 'Not saved yet.',
    'settings.saving': 'Saving settings...',
    'settings.saved': 'Saved. Incomplete AI parameters automatically fall back to local analysis.',
    'settings.aiReady': 'The required parameters for enhanced analysis are present.',
    'settings.aiFallback': 'Parameters are incomplete. The extension will use local analysis.',
    'settings.validationRequired': 'Complete required parameters before enabling AI enhanced analysis: {fields}.',
    'settings.enableAiPromptTitle': 'AI analysis is currently disabled',
    'settings.enableAiPromptBody':
      'If you keep it disabled, the extension will default to local mode and the generated result will be noticeably weaker than AI analysis.',
    'settings.enableAiPromptEnable': 'Enable AI and save',
    'settings.enableAiPromptKeepLocal': 'Save in local mode',
    'settings.enableAiPromptCancel': 'Cancel',
    'popup.currentPage': 'Current Page',
    'popup.title': 'DESIGN.md Extractor',
    'popup.localMode': 'Local Mode · Base Draft',
    'popup.hybridMode': 'AI Mode · Refined Output',
    'popup.primaryAction': 'Primary Action',
    'popup.actionTitle': 'Analyze the current page and export',
    'popup.actionCopy':
      'Without AI settings, local analysis is used. Add model URL, API key, model, and protocol to enable enhanced analysis.',
    'popup.analyzeButton': 'Analyze and generate DESIGN.md',
    'popup.settingsButton': 'Settings',
    'popup.waiting': 'Waiting to start.',
    'popup.latestResult': 'Latest Result',
    'popup.noFile': 'No file generated yet',
    'popup.noResult': 'No analysis has been run yet.',
    'popup.unsupported': 'This page cannot be analyzed. Only http/https pages are supported.',
    'popup.running': 'Collecting page data and generating DESIGN.md...',
    'popup.done': 'Analysis complete. The file has been downloaded.',
    'popup.failed': 'Analysis did not complete.',
    'popup.initFailed': 'Initialization failed.',
    'popup.noPage': 'No current page detected.',
    'popup.localPromptTitle': 'You are currently in local mode',
    'popup.localPromptBody':
      'Local mode generates a basic DESIGN.md draft immediately. AI analysis usually produces stronger structure, better language quality, and closer alignment with the reference document.',
    'popup.localPromptContinue': 'Continue locally',
    'popup.localPromptPrimary': 'Set up AI',
    'popup.localPromptSwitchAi': 'Switch to AI mode',
    'popup.localPromptCancel': 'Not now',
  },
};

const ALIASES = {
  zh: 'zh-CN',
  'zh-cn': 'zh-CN',
  'zh-hans': 'zh-CN',
  'zh-hans-cn': 'zh-CN',
  'zh-tw': 'zh-TW',
  'zh-hant': 'zh-TW',
  'zh-hant-tw': 'zh-TW',
  en: 'en',
  ja: 'ja',
  ko: 'ko',
  fr: 'fr',
  de: 'de',
  es: 'es',
};

const MACHINE_TRANSLATIONS = {
  'zh-TW': {
    'settings.title': 'DESIGN.md Extractor 設定',
    'settings.heroEyebrow': '混合分析器',
    'settings.heroCopy':
      '外掛預設可在本機規則模式下運作。填寫模型地址、API Key、模型名稱和協議後，會自動切換到增強分析模式。',
    'settings.aiEyebrow': '模型',
    'settings.analysisEyebrow': '分析',
    'settings.rulesEyebrow': '規則',
    'settings.aiSettings': '模型連線參數',
    'settings.enableAi': '啟動 AI',
    'settings.uiLanguage': '當前語言',
    'settings.protocol': '協議',
    'settings.baseUrl': 'Base URL',
    'settings.model': '模型名稱',
    'settings.endpointPath': 'Endpoint Path',
    'settings.apiKey': 'API Key',
    'settings.temperature': 'Temperature',
    'settings.maxOutputTokens': 'Max Output Tokens',
    'settings.timeoutMs': 'Timeout (ms)',
    'settings.outputLanguage': '輸出語言',
    'settings.systemPromptOverride': 'System Prompt Override',
    'settings.analysisTitle': '分析與匯出偏好',
    'settings.redactInputs': '遮罩輸入內容',
    'settings.autoDownloadAfterGeneration': '自動下載生成結果',
    'settings.includeColorTokens': '包含顏色 token',
    'settings.includeTypographyTokens': '包含字體 token',
    'settings.includeSpacingHeuristics': '包含間距啟發式分析',
    'settings.includeRawAuditAppendix': '附加原始稽核附錄',
    'settings.includeFrontmatter': '包含 Frontmatter',
    'settings.maxDomNodes': '最大節點數',
    'settings.filenameTemplate': '檔名範本',
    'settings.rulesTitle': '站點規則與隱私說明',
    'settings.siteAllowlist': '允許清單（每行一個網域片段，可留空）',
    'settings.siteBlocklist': '排除清單（每行一個網域片段）',
    'settings.privacyNote':
      '啟用 AI 增強分析時，外掛會將結構化頁面摘要傳送到你設定的遠端模型介面，不會直接上傳完整原始 DOM。',
    'settings.saveButton': '儲存設定',
    'settings.unsaved': '尚未儲存。',
    'settings.saving': '正在儲存設定...',
    'settings.saved': '已儲存。未設定完整 AI 參數時，外掛會自動使用本機規則分析。',
    'settings.aiReady': '目前已具備增強分析所需的基礎參數。',
    'settings.aiFallback': '目前參數不完整，外掛將自動退回本機規則分析。',
    'settings.validationRequired': '啟用 AI 增強分析時，請先補齊必要參數：{fields}。',
    'popup.currentPage': '目前頁面',
    'popup.title': 'DESIGN.md Extractor',
    'popup.localMode': '目前為本機基礎分析模式',
    'popup.hybridMode': '增強分析模式已啟用',
    'popup.primaryAction': '主要操作',
    'popup.actionTitle': '分析目前頁面並直接匯出',
    'popup.actionCopy':
      '未設定 AI 時自動使用本機規則分析。補齊模型地址、API Key、模型名稱和協議後，會自動啟用增強分析。',
    'popup.analyzeButton': '分析並匯出 DESIGN.md',
    'popup.settingsButton': '開啟設定',
    'popup.waiting': '等待開始。',
    'popup.latestResult': '最近一次分析',
    'popup.noFile': '尚未生成檔案',
    'popup.noResult': '尚未執行分析。',
    'popup.unsupported': '目前頁面不可分析，僅支援 http/https 頁面。',
    'popup.running': '正在擷取頁面並生成 DESIGN.md...',
    'popup.done': '分析完成，檔案已下載到本機。',
    'popup.failed': '分析未完成。',
    'popup.initFailed': '初始化失敗。',
    'popup.noPage': '未偵測到目前頁面。',
  },
  ja: {
    'settings.title': 'DESIGN.md Extractor 設定',
    'settings.heroEyebrow': 'ハイブリッド分析',
    'settings.heroCopy':
      'この拡張機能はデフォルトでローカルルール分析を使用します。モデル URL、API Key、モデル名、プロトコルを入力すると、拡張分析が有効になります。',
    'settings.aiEyebrow': 'モデル',
    'settings.analysisEyebrow': '分析',
    'settings.rulesEyebrow': 'ルール',
    'settings.aiSettings': 'モデル接続パラメータ',
    'settings.enableAi': 'AI を有効化',
    'settings.protocol': 'プロトコル',
    'settings.baseUrl': 'Base URL',
    'settings.model': 'モデル名',
    'settings.endpointPath': 'Endpoint Path',
    'settings.apiKey': 'API Key',
    'settings.temperature': 'Temperature',
    'settings.maxOutputTokens': 'Max Output Tokens',
    'settings.timeoutMs': 'Timeout (ms)',
    'settings.analysisTitle': '分析とエクスポート設定',
    'settings.redactInputs': '入力内容をマスク',
    'settings.autoDownloadAfterGeneration': '生成後に自動ダウンロード',
    'settings.includeColorTokens': 'カラー token を含める',
    'settings.includeTypographyTokens': 'フォント token を含める',
    'settings.includeSpacingHeuristics': '間隔ヒューリスティックを含める',
    'settings.includeRawAuditAppendix': '元分析の付録を追加',
    'settings.includeFrontmatter': 'Frontmatter を含める',
    'settings.maxDomNodes': '最大 DOM ノード数',
    'settings.filenameTemplate': 'ファイル名テンプレート',
    'settings.rulesTitle': 'サイトルールとプライバシー',
    'settings.siteAllowlist': '許可リスト（1 行に 1 つのドメイン断片、省略可）',
    'settings.siteBlocklist': '除外リスト（1 行に 1 つのドメイン断片）',
    'settings.privacyNote':
      'AI 拡張分析を有効にすると、完全な生 DOM ではなく、構造化されたページ概要が設定済みのモデル API に送信されます。',
    'settings.saveButton': '設定を保存',
    'settings.unsaved': 'まだ保存されていません。',
    'settings.saving': '設定を保存しています...',
    'settings.saved': '保存しました。AI パラメータが不完全な場合はローカル分析を使用します。',
    'settings.aiReady': '拡張分析に必要な基本パラメータが揃っています。',
    'settings.aiFallback': 'パラメータが不完全です。ローカルルール分析に戻ります。',
    'settings.uiLanguage': '現在の言語',
    'settings.outputLanguage': '出力言語',
    'settings.systemPromptOverride': 'System Prompt Override',
    'popup.currentPage': '現在のページ',
    'popup.title': 'DESIGN.md Extractor',
    'popup.localMode': 'ローカル基本分析モード',
    'popup.hybridMode': '拡張分析モードが有効です',
    'popup.primaryAction': '主な操作',
    'popup.actionTitle': '現在のページを分析して直接エクスポート',
    'popup.actionCopy':
      'AI が未設定の場合はローカル分析を使用します。モデル URL、API Key、モデル名、プロトコルを入力すると拡張分析が有効になります。',
    'popup.settingsButton': '設定を開く',
    'popup.analyzeButton': 'DESIGN.md を分析してエクスポート',
    'popup.waiting': '開始待ちです。',
    'popup.latestResult': '最新の分析結果',
    'popup.noFile': 'まだファイルは生成されていません',
    'popup.noResult': 'まだ分析は実行されていません。',
    'popup.unsupported': 'このページは分析できません。http/https ページのみ対応しています。',
    'popup.running': 'ページ情報を収集し、DESIGN.md を生成しています...',
    'popup.done': '分析が完了しました。ファイルをダウンロードしました。',
    'popup.failed': '分析は完了しませんでした。',
    'popup.initFailed': '初期化に失敗しました。',
    'popup.noPage': '現在のページを検出できません。',
  },
  ko: {
    'settings.title': 'DESIGN.md Extractor 설정',
    'settings.heroEyebrow': '하이브리드 분석기',
    'settings.heroCopy':
      '이 확장 프로그램은 기본적으로 로컬 규칙 분석을 사용합니다. 모델 주소, API Key, 모델명, 프로토콜을 입력하면 향상된 분석이 자동으로 활성화됩니다.',
    'settings.aiEyebrow': '모델',
    'settings.analysisEyebrow': '분석',
    'settings.rulesEyebrow': '규칙',
    'settings.aiSettings': '모델 연결 매개변수',
    'settings.enableAi': 'AI 사용',
    'settings.protocol': '프로토콜',
    'settings.baseUrl': 'Base URL',
    'settings.model': '모델명',
    'settings.endpointPath': 'Endpoint Path',
    'settings.apiKey': 'API Key',
    'settings.temperature': 'Temperature',
    'settings.maxOutputTokens': 'Max Output Tokens',
    'settings.timeoutMs': 'Timeout (ms)',
    'settings.analysisTitle': '분석 및 내보내기 설정',
    'settings.redactInputs': '입력 내용 마스킹',
    'settings.autoDownloadAfterGeneration': '생성 후 자동 다운로드',
    'settings.includeColorTokens': '색상 token 포함',
    'settings.includeTypographyTokens': '글꼴 token 포함',
    'settings.includeSpacingHeuristics': '간격 휴리스틱 포함',
    'settings.includeRawAuditAppendix': '원본 분석 부록 추가',
    'settings.includeFrontmatter': 'Frontmatter 포함',
    'settings.maxDomNodes': '최대 DOM 노드 수',
    'settings.filenameTemplate': '파일명 템플릿',
    'settings.rulesTitle': '사이트 규칙 및 개인정보',
    'settings.siteAllowlist': '허용 목록（한 줄에 도메인 조각 하나, 선택 사항）',
    'settings.siteBlocklist': '차단 목록（한 줄에 도메인 조각 하나）',
    'settings.privacyNote':
      'AI 향상 분석을 사용하면 전체 원본 DOM 이 아니라 구조화된 페이지 요약이 설정한 모델 API 로 전송됩니다.',
    'settings.saveButton': '설정 저장',
    'settings.unsaved': '아직 저장되지 않았습니다.',
    'settings.saving': '설정을 저장하는 중...',
    'settings.saved': '저장되었습니다. AI 매개변수가 불완전하면 로컬 분석을 사용합니다.',
    'settings.aiReady': '향상된 분석에 필요한 기본 매개변수가 준비되었습니다.',
    'settings.aiFallback': '매개변수가 불완전하여 로컬 규칙 분석을 사용합니다.',
    'settings.uiLanguage': '현재 언어',
    'settings.outputLanguage': '출력 언어',
    'settings.systemPromptOverride': 'System Prompt Override',
    'popup.currentPage': '현재 페이지',
    'popup.title': 'DESIGN.md Extractor',
    'popup.localMode': '로컬 기본 분석 모드',
    'popup.hybridMode': '향상된 분석 모드가 활성화됨',
    'popup.primaryAction': '주요 작업',
    'popup.actionTitle': '현재 페이지 분석 및 바로 내보내기',
    'popup.actionCopy':
      'AI 설정이 없으면 로컬 분석을 사용합니다. 모델 주소, API Key, 모델명, 프로토콜을 입력하면 향상된 분석이 활성화됩니다.',
    'popup.settingsButton': '설정 열기',
    'popup.analyzeButton': 'DESIGN.md 분석 및 내보내기',
    'popup.waiting': '시작 대기 중입니다.',
    'popup.latestResult': '최근 분석 결과',
    'popup.noFile': '아직 생성된 파일이 없습니다',
    'popup.noResult': '아직 분석을 실행하지 않았습니다.',
    'popup.unsupported': '이 페이지는 분석할 수 없습니다. http/https 페이지만 지원합니다.',
    'popup.running': '페이지 데이터를 수집하고 DESIGN.md 를 생성하는 중...',
    'popup.done': '분석이 완료되었습니다. 파일이 다운로드되었습니다.',
    'popup.failed': '분석이 완료되지 않았습니다.',
    'popup.initFailed': '초기화에 실패했습니다.',
    'popup.noPage': '현재 페이지를 감지하지 못했습니다.',
  },
  fr: {
    'settings.title': 'Paramètres de DESIGN.md Extractor',
    'settings.heroEyebrow': 'Analyseur hybride',
    'settings.heroCopy':
      "L'extension fonctionne localement par défaut. Ajoutez l'URL du modèle, la clé API, le modèle et le protocole pour activer l'analyse améliorée.",
    'settings.aiEyebrow': 'Modèle',
    'settings.analysisEyebrow': 'Analyse',
    'settings.rulesEyebrow': 'Règles',
    'settings.aiSettings': 'Paramètres de connexion au modèle',
    'settings.enableAi': "Activer l'IA",
    'settings.protocol': 'Protocole',
    'settings.baseUrl': 'Base URL',
    'settings.model': 'Modèle',
    'settings.endpointPath': 'Endpoint Path',
    'settings.apiKey': 'API Key',
    'settings.temperature': 'Temperature',
    'settings.maxOutputTokens': 'Max Output Tokens',
    'settings.timeoutMs': 'Timeout (ms)',
    'settings.analysisTitle': "Préférences d'analyse et d'export",
    'settings.redactInputs': 'Masquer le contenu saisi',
    'settings.autoDownloadAfterGeneration': 'Télécharger automatiquement le résultat',
    'settings.includeColorTokens': 'Inclure les color tokens',
    'settings.includeTypographyTokens': 'Inclure les typography tokens',
    'settings.includeSpacingHeuristics': "Inclure l'analyse heuristique des espacements",
    'settings.includeRawAuditAppendix': "Ajouter l'annexe d'audit brut",
    'settings.includeFrontmatter': 'Inclure le Frontmatter',
    'settings.maxDomNodes': 'Nombre maximal de nœuds DOM',
    'settings.filenameTemplate': 'Modèle de nom de fichier',
    'settings.rulesTitle': 'Règles de site et confidentialité',
    'settings.siteAllowlist': 'Liste autorisée (un fragment de domaine par ligne, optionnel)',
    'settings.siteBlocklist': 'Liste bloquée (un fragment de domaine par ligne)',
    'settings.privacyNote':
      "Quand l'analyse IA est activée, l'extension envoie un résumé structuré de la page à votre endpoint de modèle, pas le DOM brut complet.",
    'settings.saveButton': 'Enregistrer les paramètres',
    'settings.unsaved': 'Pas encore enregistré.',
    'settings.saving': 'Enregistrement des paramètres...',
    'settings.saved': "Enregistré. Si les paramètres IA sont incomplets, l'analyse locale sera utilisée.",
    'settings.aiReady': "Les paramètres requis pour l'analyse améliorée sont présents.",
    'settings.aiFallback': "Paramètres incomplets. L'extension utilisera l'analyse locale.",
    'settings.uiLanguage': 'Langue actuelle',
    'settings.outputLanguage': 'Langue de sortie',
    'settings.systemPromptOverride': 'System Prompt Override',
    'popup.currentPage': 'Page actuelle',
    'popup.title': 'DESIGN.md Extractor',
    'popup.localMode': "Mode d'analyse locale",
    'popup.hybridMode': "Mode d'analyse améliorée activé",
    'popup.primaryAction': 'Action principale',
    'popup.actionTitle': 'Analyser la page actuelle et exporter',
    'popup.actionCopy':
      "Sans paramètres IA, l'analyse locale est utilisée. Ajoutez l'URL du modèle, la clé API, le modèle et le protocole pour activer l'analyse améliorée.",
    'popup.settingsButton': 'Ouvrir les paramètres',
    'popup.analyzeButton': 'Analyser et exporter DESIGN.md',
    'popup.waiting': 'En attente de démarrage.',
    'popup.latestResult': 'Dernier résultat',
    'popup.noFile': 'Aucun fichier généré',
    'popup.noResult': "Aucune analyse n'a encore été lancée.",
    'popup.unsupported': 'Cette page ne peut pas être analysée. Seules les pages http/https sont prises en charge.',
    'popup.running': 'Collecte de la page et génération de DESIGN.md...',
    'popup.done': 'Analyse terminée. Le fichier a été téléchargé.',
    'popup.failed': "L'analyse n'a pas abouti.",
    'popup.initFailed': "Échec de l'initialisation.",
    'popup.noPage': 'Aucune page actuelle détectée.',
  },
  de: {
    'settings.title': 'DESIGN.md Extractor Einstellungen',
    'settings.heroEyebrow': 'Hybrid-Analyzer',
    'settings.heroCopy':
      'Die Erweiterung arbeitet standardmäßig lokal. Fügen Sie Modell-URL, API Key, Modell und Protokoll hinzu, um die erweiterte Analyse zu aktivieren.',
    'settings.aiEyebrow': 'Modell',
    'settings.analysisEyebrow': 'Analyse',
    'settings.rulesEyebrow': 'Regeln',
    'settings.aiSettings': 'Modellverbindung',
    'settings.enableAi': 'KI aktivieren',
    'settings.protocol': 'Protokoll',
    'settings.baseUrl': 'Base URL',
    'settings.model': 'Modell',
    'settings.endpointPath': 'Endpoint Path',
    'settings.apiKey': 'API Key',
    'settings.temperature': 'Temperature',
    'settings.maxOutputTokens': 'Max Output Tokens',
    'settings.timeoutMs': 'Timeout (ms)',
    'settings.analysisTitle': 'Analyse- und Exportoptionen',
    'settings.redactInputs': 'Eingabeinhalte maskieren',
    'settings.autoDownloadAfterGeneration': 'Ergebnis automatisch herunterladen',
    'settings.includeColorTokens': 'Farb-Tokens einschließen',
    'settings.includeTypographyTokens': 'Typografie-Tokens einschließen',
    'settings.includeSpacingHeuristics': 'Abstands-Heuristiken einschließen',
    'settings.includeRawAuditAppendix': 'Roh-Audit-Anhang hinzufügen',
    'settings.includeFrontmatter': 'Frontmatter einschließen',
    'settings.maxDomNodes': 'Maximale DOM-Knoten',
    'settings.filenameTemplate': 'Dateinamenvorlage',
    'settings.rulesTitle': 'Website-Regeln und Datenschutz',
    'settings.siteAllowlist': 'Allowlist (ein Domainfragment pro Zeile, optional)',
    'settings.siteBlocklist': 'Blocklist (ein Domainfragment pro Zeile)',
    'settings.privacyNote':
      'Bei aktivierter KI-Analyse sendet die Erweiterung eine strukturierte Seitenzusammenfassung an den konfigurierten Modell-Endpunkt, nicht den vollständigen DOM.',
    'settings.saveButton': 'Einstellungen speichern',
    'settings.unsaved': 'Noch nicht gespeichert.',
    'settings.saving': 'Einstellungen werden gespeichert...',
    'settings.saved': 'Gespeichert. Unvollständige KI-Parameter fallen automatisch auf lokale Analyse zurück.',
    'settings.aiReady': 'Die erforderlichen Parameter für die erweiterte Analyse sind vorhanden.',
    'settings.aiFallback': 'Parameter unvollständig. Die Erweiterung verwendet lokale Analyse.',
    'settings.uiLanguage': 'Aktuelle Sprache',
    'settings.outputLanguage': 'Ausgabesprache',
    'settings.systemPromptOverride': 'System Prompt Override',
    'popup.currentPage': 'Aktuelle Seite',
    'popup.title': 'DESIGN.md Extractor',
    'popup.localMode': 'Lokaler Analysemodus',
    'popup.hybridMode': 'Erweiterter Analysemodus aktiviert',
    'popup.primaryAction': 'Hauptaktion',
    'popup.actionTitle': 'Aktuelle Seite analysieren und exportieren',
    'popup.actionCopy':
      'Ohne KI-Einstellungen wird lokale Analyse verwendet. Fügen Sie Modell-URL, API Key, Modell und Protokoll hinzu, um die erweiterte Analyse zu aktivieren.',
    'popup.settingsButton': 'Einstellungen öffnen',
    'popup.analyzeButton': 'DESIGN.md analysieren und exportieren',
    'popup.waiting': 'Warten auf Start.',
    'popup.latestResult': 'Letztes Ergebnis',
    'popup.noFile': 'Noch keine Datei erzeugt',
    'popup.noResult': 'Noch keine Analyse ausgeführt.',
    'popup.unsupported': 'Diese Seite kann nicht analysiert werden. Nur http/https-Seiten werden unterstützt.',
    'popup.running': 'Seitendaten werden gesammelt und DESIGN.md wird generiert...',
    'popup.done': 'Analyse abgeschlossen. Die Datei wurde heruntergeladen.',
    'popup.failed': 'Analyse wurde nicht abgeschlossen.',
    'popup.initFailed': 'Initialisierung fehlgeschlagen.',
    'popup.noPage': 'Keine aktuelle Seite erkannt.',
  },
  es: {
    'settings.title': 'Configuración de DESIGN.md Extractor',
    'settings.heroEyebrow': 'Analizador híbrido',
    'settings.heroCopy':
      'La extensión funciona localmente de forma predeterminada. Añade URL del modelo, API Key, modelo y protocolo para activar el análisis mejorado.',
    'settings.aiEyebrow': 'Modelo',
    'settings.analysisEyebrow': 'Análisis',
    'settings.rulesEyebrow': 'Reglas',
    'settings.aiSettings': 'Parámetros de conexión del modelo',
    'settings.enableAi': 'Activar IA',
    'settings.protocol': 'Protocolo',
    'settings.baseUrl': 'Base URL',
    'settings.model': 'Modelo',
    'settings.endpointPath': 'Endpoint Path',
    'settings.apiKey': 'API Key',
    'settings.temperature': 'Temperature',
    'settings.maxOutputTokens': 'Max Output Tokens',
    'settings.timeoutMs': 'Timeout (ms)',
    'settings.analysisTitle': 'Preferencias de análisis y exportación',
    'settings.redactInputs': 'Ocultar contenido de entrada',
    'settings.autoDownloadAfterGeneration': 'Descargar resultado automáticamente',
    'settings.includeColorTokens': 'Incluir tokens de color',
    'settings.includeTypographyTokens': 'Incluir tokens tipográficos',
    'settings.includeSpacingHeuristics': 'Incluir heurísticas de espaciado',
    'settings.includeRawAuditAppendix': 'Añadir apéndice de auditoría sin procesar',
    'settings.includeFrontmatter': 'Incluir Frontmatter',
    'settings.maxDomNodes': 'Máximo de nodos DOM',
    'settings.filenameTemplate': 'Plantilla de nombre de archivo',
    'settings.rulesTitle': 'Reglas del sitio y privacidad',
    'settings.siteAllowlist': 'Lista permitida (un fragmento de dominio por línea, opcional)',
    'settings.siteBlocklist': 'Lista bloqueada (un fragmento de dominio por línea)',
    'settings.privacyNote':
      'Cuando el análisis con IA está activado, la extensión envía un resumen estructurado de la página al endpoint configurado, no el DOM completo.',
    'settings.saveButton': 'Guardar configuración',
    'settings.unsaved': 'Aún no guardado.',
    'settings.saving': 'Guardando configuración...',
    'settings.saved': 'Guardado. Si los parámetros de IA están incompletos, se usará el análisis local.',
    'settings.aiReady': 'Los parámetros necesarios para el análisis mejorado están presentes.',
    'settings.aiFallback': 'Los parámetros están incompletos. La extensión usará análisis local.',
    'settings.uiLanguage': 'Idioma actual',
    'settings.outputLanguage': 'Idioma de salida',
    'settings.systemPromptOverride': 'System Prompt Override',
    'popup.currentPage': 'Página actual',
    'popup.title': 'DESIGN.md Extractor',
    'popup.localMode': 'Modo de análisis local',
    'popup.hybridMode': 'Modo de análisis mejorado activado',
    'popup.primaryAction': 'Acción principal',
    'popup.actionTitle': 'Analizar la página actual y exportar',
    'popup.actionCopy':
      'Sin configuración de IA se usa análisis local. Añade URL del modelo, API Key, modelo y protocolo para activar el análisis mejorado.',
    'popup.settingsButton': 'Abrir configuración',
    'popup.analyzeButton': 'Analizar y exportar DESIGN.md',
    'popup.waiting': 'Esperando para comenzar.',
    'popup.latestResult': 'Último resultado',
    'popup.noFile': 'Aún no se ha generado ningún archivo',
    'popup.noResult': 'Aún no se ha ejecutado ningún análisis.',
    'popup.unsupported': 'Esta página no se puede analizar. Solo se admiten páginas http/https.',
    'popup.running': 'Recopilando datos de la página y generando DESIGN.md...',
    'popup.done': 'Análisis completado. El archivo se ha descargado.',
    'popup.failed': 'El análisis no se completó.',
    'popup.initFailed': 'Error de inicialización.',
    'popup.noPage': 'No se detectó ninguna página actual.',
  },
};

for (const [language, translations] of Object.entries(MACHINE_TRANSLATIONS)) {
  UI_MESSAGES[language] = {
    ...UI_MESSAGES.en,
    ...translations,
  };
  TOOLTIP_COPY_BY_LANGUAGE[language] ||= TOOLTIP_COPY_BY_LANGUAGE.en;
}

export function resolveSupportedLanguage(language) {
  const normalized = String(language || '').trim().toLowerCase();
  if (!normalized) {
    return 'en';
  }

  if (ALIASES[normalized]) {
    return ALIASES[normalized];
  }

  const base = normalized.split('-')[0];
  return ALIASES[base] || 'en';
}

export function getMessage(language, key) {
  const resolved = resolveSupportedLanguage(language);
  return UI_MESSAGES[resolved]?.[key] || UI_MESSAGES.en[key] || UI_MESSAGES['zh-CN'][key] || key;
}

export function getTooltipCopy(language, key) {
  const resolved = resolveSupportedLanguage(language);
  return TOOLTIP_COPY_BY_LANGUAGE[resolved]?.[key] || TOOLTIP_COPY_BY_LANGUAGE.en[key] || key;
}

export function getLanguageLabel(language) {
  const resolved = resolveSupportedLanguage(language);
  return LANGUAGE_OPTIONS.find((option) => option.value === resolved)?.label || 'English';
}
